# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
   branches: ["main"]
  # pull_request:
  #   branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Contains a Code Cleanup Job with ABAP Cleaner and triggers auto commit
  Code-Cleanup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Download ABAP Cleaner
        run: |
          mkdir .cleanup
          cd .cleanup
          wget -q -c https://github.com/SAP/abap-cleaner/releases/download/v1.5.5/com.sap.adt.abapcleaner.app-linux.gtk.x86_64.tar.gz -O - | tar -xz
          cd ..

      - name: Clean-up files in /src
        run: ./.cleanup/abapcleaner/abap-cleaner --sourcefile src/zcl_abap_class.clas.abap --targetfile src/zcl_abap_class.clas.abap --overwrite --profile ${{ github.workspace }}/cleaner-profile.cfj --release 750

      # Commit the changes
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          #author_name: Ludwig Stockbauer-Muhr
          #author_email: stocki87@gmail.com
          message: "style: code cleanup with ABAP cleaner"
          add: "src"
